#!/bin/bash
CURRPWD=`dirname "$0"`
if [[ -e "$CURRPWD/source/ISDEV.sh" ]]; then
    source "$CURRPWD/source/ISDEV.sh"
fi
EXP_DIR="$HOME/experiments"
EXPERIMENT="PAL"
EXPERIMENT_NUM="3"
EXPERIMENT_DIR="RAM_$EXPERIMENT"
CONFIG="config.py"
SCONFIG="PAL3_config.py"
PYTHON_CMD="python2.6"

DOLOG=1
RAM_DIR=$CURRPWD

export PYTHONPATH="$PYTHONPATH:$RAM_DIR/source/pylib"

ARCHIVE_DIR="$RAM_DIR/data/${EXPERIMENT}${EXPERIMENT_NUM}/"
RESOLUTION="1440x900"
NOFS=0
LOGS_DIR="$RAM_DIR/logs"
LOG_FILE="$LOGS_DIR/${EXPERIMENT}${EXPERIMENT_NUM}.log"

cd $EXP_DIR/$EXPERIMENT_DIR/
mkdir -p $LOGS_DIR
echo "****************************************">>$LOG_FILE
date >> $LOG_FILE 

if [[ $IS_DEV == 1 ]];then
    cd branches/dev
    echo "DEV BRANCH"  >> $LOG_FILE
elif [[ -e branches/sys2 ]]; then
    cd branches/sys2
    echo "SYS2" >> $LOG_FILE
fi

if [[ $SCONFIG != "" ]]; then
    SCONFIG_OPTION="--sconfig=$SCONFIG"
fi

if [[ "$NOFS" == "1" ]]; then
    NOFS_OPTION="--no-fs"
fi



# GET THE SUBJECT 

while [[ $SUBJ_NUM == "" ]]; do
    echo "ENTER SUBJECT CODE (subject codes containing \"test\" will not be recorded): "
    read SUBJ_NUM
done


if [[ $SUBJ_NUM =~ .*test.* ]]; then
    ARCHIVE_DIR="$HOME/test_data"
    rm -rf $ARCHIVE_DIR
fi
mkdir -p $ARCHIVE_DIR

OPTIONS="-s $SUBJ_NUM --config=$CONFIG $SCONFIG_OPTION --resolution=$RESOLUTION $NOFS_OPTION --archive=$ARCHIVE_DIR"

# RUNNING THE ACTUAL EXPERIMENT

echo $SUBJ_NUM >> $LOG_FILE

if [[ "$DOLOG" == "1" ]]; then
    $PYTHON_CMD $EXPERIMENT.py $OPTIONS 2>&1 | tee -a $LOG_FILE
else
    $PYTHON_CMD $EXPERIMENT.py $OPTIONS 
fi

if [[ -e $HOME/test_data ]]; then 
    rm -rf $HOME/test_data
fi

echo "Finished. Press enter to exit"; 
read
